INSERT INTO Customer (cust_id, name, phone, address, email) 
VALUES ('1','Kami Clow', '801-111-2222','123 Street','kami@gmail.com')
INSERT INTO Customer (cust_id, name, phone, address, email) 
VALUES ('2','Steve Sow', '801-111-2233', '45 W 100 E','steve@gmail.com')	
INSERT INTO Customer (cust_id, name, phone, address, email) 
VALUES ('3','Linder Johns', '801-111-2244', 'Applewood Way','linderJ@buyers.com')

INSERT INTO PaymentInfo (card, cash, b_address, cust_id) 
VALUES ('1','0','10 E 1250 N','1')
INSERT INTO PaymentInfo (card, cash, b_address, cust_id) 
VALUES ('1','0','Johnsonville drive','2')
INSERT INTO PaymentInfo (card, cash, b_address, cust_id) 
VALUES ('0','1','Applewood Way','3')

INSERT INTO CreditCard (card_number, cared_type, exp_date) 
VALUES ('1111-222-3333-4444','visa','05/20')
INSERT INTO CreditCard (card_number, cared_type, exp_date) 
VALUES ('2222-333-4444-5555','amex','01/21')

INSERT INTO Cash (type, total)
VALUES ('$','50')

INSERT INTO Orders (order_id, order_date) 
VALUES ('1','2018-01-01')
INSERT INTO Orders (order_id, order_date) 
VALUES ('2','2018-01-01')

INSERT INTO Product (p_id, p_name, p_type, p_color, p_weight) 
VALUES ('1','basic','cotton','white','5')
INSERT INTO Product (p_id, p_name, p_type, p_color, p_weight) 
VALUES ('2','basic','cotton','black','5')
INSERT INTO Product (p_id, p_name, p_type, p_color, p_weight) 
VALUES ('3','basic','cotton','red','5')
INSERT INTO Product (p_id, p_name, p_type, p_color, p_weight) 
VALUES ('4','basic','cotton','blue','5')
INSERT INTO Product (p_id, p_name, p_type, p_color, p_weight) 
VALUES ('5','basic','cotton','yellow','5')

INSERT INTO Vendors (vendor_id, vendor_name) 
VALUES ('1','Cotton Vendor')
INSERT INTO Vendors (vendor_id, vendor_name) 
VALUES ('2','Textile Vendor')

INSERT INTO Employee (employeeID, name, address, phone_number) 
VALUES ('1','Austin Cloward','2093 N 40 W','801-111-2222')
INSERT INTO Employee (employeeID, name, address, phone_number) 
VALUES ('2','John Smith','250 Driveby','801-134-5211')

INSERT INTO Admin (username, password) 
VALUES ('admin','My@pwd321')